
trigger:
- main

pool:
  vmImage: ubuntu-latest
  parallel: 1

steps:


- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'naymul24/webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.txt'
    tags: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Naymul Islam DevOps(148be6f4-2480-48a8-9977-4d2ce0812c4c)'
    azureResourceGroup: 'networking-resource-group'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'aks-terraform/application-manifest.yaml'